### ISSUE TITLE
Simplejson is faster and requires less class generation why it is not used in the GLTF utility?

### ISSUE THREAD

**Issue by AzadNezamdoust** [Siccity/GLTFUtility#55]
Simplejson is faster and requires less class generation why it is not used in the GLTF utility? I need to get the best performance for the mobile I wonder if newton json has some essential features simple json does not.

**Comment by Siccity** [comment]
Having json fields bound to a c# class variable is a good thing imo. It helps with the overview through autocomplete and you avoid having to look up the GLTF spec when dealing with the parsed data.

As for speed I can't say. I don't think json parsing is the most significant factor in GLTF import speed. I chose Newtonsoft because it is very battle tested and officially supported.

If there are any significant benefits in swapping to simplejson i will consider it.
